# Use the official Python base image
FROM python:3.9

# Set working directory inside the container
WORKDIR /app

# Copy the app.py file into the container
COPY app.py .

# Run the Python file when the container starts
CMD ["python", "app.py"]
